### ISSUE TITLE
[feat] - CandidateCancelModal 구현

### ISSUE THREAD

**Issue by jinyoung234** [dnd-side-project/dnd-8th-1-frontend#138]
# 개요
CandidateCancelModal 구현

# 작업 내용
- [ ] CandidateCancelModal 구현

# 타 직군 전달 사항

## 디자이너 전달 사항

# 기타

**Comment by dar-jeeling** [comment]
![image](https://user-images.githubusercontent.com/74234333/219846452-229d5d38-247f-4cf7-a027-eb7ce0d12bcf.png)

혹시 이 모달이라면 구현 완료했습니다!
