### ISSUE TITLE
[feat] - 공연 상세 페이지 mutate 관련 서버 통신 구현 

### ISSUE THREAD

**Issue by punchdrunkard** [dnd-side-project/dnd-8th-1-frontend#226]
# 개요

 공연 상세 페이지 mutate 관련 서버 통신 구현 

# 작업 내용

- [ ] review 관련 기능 테스트

# 타 직군 전달 사항

## 디자이너 전달 사항

# 기타

**Comment by dar-jeeling** [comment]
#299
