### ISSUE TITLE
[feat] - Icon 컴포넌트 구현

### ISSUE THREAD

**Issue by punchdrunkard** [dnd-side-project/dnd-8th-1-frontend#23]
# 개요

Icon 컴포넌트를 구현합니다.

# 작업 내용

- [ ] props로 svg 를 그대로 받아온다. 
- [ ] 아이콘이 확정되면 해당 아이콘은 props로 타입을 정한다. (우선은 관련 부분 주석 처리)

# 기타
참고자료 :
[React에서 Icon 다루기 | Medium](https://blog.toycrane.xyz/react%EC%97%90%EC%84%9C-icon-%EB%8B%A4%EB%A3%A8%EA%B8%B0-59b6d987d61f)
[React Custom Icon Component 개발기 | SOCA Tech Blog](https://tech.socarcorp.kr/dev/2022/09/06/react-icon-component.html)

**Comment by punchdrunkard** [comment]
각 아이콘의 `path`와 `viewbox` 값을 지정해야 하므로, 아이콘 시스템이 나와야 구현 할 수 있을 듯 싶네요 ㅠㅠ @jinyoung234

**Comment by jinyoung234** [comment]
아니면 더미 아이콘 하나 가져오는건 좀 별로일까여 .. ?!

**Comment by punchdrunkard** [comment]
좋네요! 더미 아이콘 하나 가져오고 시스템만 우선 만들게요!
