### ISSUE TITLE
[refactor] - SearchResultHeader, SearchHeader, PerformanceEntireList, SearchResultList 컴포넌트 설계 변경

### ISSUE THREAD

**Issue by jinyoung234** [dnd-side-project/dnd-8th-1-frontend#352]
# 개요
컴포넌트에 대한 Headless 컴포넌트 생성 후 RenderProps 패턴 적용을 위한 리팩토링 진행

# 작업 내용
- [ ] useWithDatePerformances hook 생성
- [ ] PerformancesWithDateHeadless 컴포넌트 개발
- [ ] PerformancesWithDateHeadless 컴포넌트 PerformanceEntireList와 SearchResultList에 적용

# 타 직군 전달 사항

## 디자이너 전달 사항

# 기타

**Comment by punchdrunkard** [comment]
커스텀 훅 이름을 `useWithDatePerformances` 보다는 `usePerformancesWithDate`로 변경하는게 좋지 않을까요?
이전의 이름의 경우, 표현이 약간 모호하고 의미 전달이 불분명합니다. (중요한건 WithDate가 아니라 Performance니깐요)
또한, 순서가 뒤바뀌어 있어서 일반적인 영어 표현과는 다소 거리가 있어서 처음 이름을 보았을 때, 무슨 뜻인지 이해하기 어렵습니다.
