### ISSUE TITLE
[fix] - 요청 서버 url 변경

### ISSUE THREAD

**Issue by jinyoung234** [dnd-side-project/dnd-8th-1-frontend#356]
# 개요
기존 서버 종료 후 새로운 서버 켬에 따라 요청 서버 url 변경 작업 진행

# 작업 내용
- [ ] 환경 변수 파일에 요청 서버 url 변경

# 타 직군 전달 사항

## 디자이너 전달 사항

# 기타

**Comment by punchdrunkard** [comment]
지금 확인했네요..
이건 푸시되는 내용은 아니라서 따로 저장소에 반영은 안해도 될 것 같습니다.
다만 next/image 관련으로 cdn 주소가 변하는게 있을까요?

**Comment by jinyoung234** [comment]
> 지금 확인했네요.. 이건 푸시되는 내용은 아니라서 따로 저장소에 반영은 안해도 될 것 같습니다. 다만 next/image 관련으로 cdn 주소가 변하는게 있을까요?

아 제가 착각했네여,,,ㅎ 아니여 따로 없습니다!! 이슈는 삭제하도록 할게여
