### ISSUE TITLE
[feat] - CollaboList 컴포넌트 제작 

### ISSUE THREAD

**Issue by punchdrunkard** [dnd-side-project/dnd-8th-1-frontend#66]
# 개요

CollaboList 컴포넌트 제작 

# 작업 내용

![image](https://user-images.githubusercontent.com/74234333/218650712-b34842e6-f820-4008-8ff6-23e893636002.png)

- [ ] ColloaboListItem 컴포넌트 제작
- [ ] 무한 스크롤 존재 (페이지에서..)

# 타 직군 전달 사항

## 디자이너 전달 사항

# 기타

**Comment by jinyoung234** [comment]
p3; Collabo 보단 쉐어 게시물들도 있어서 MeetList가 맞는 성격이라고 생각하는데 다은님 의견은 어떠신가여?
